version: "3.9"

name: "workers_bot_container"
services:
  database:
    container_name: "workers_db"
    image: "postgres:16.3"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=roman"
      - "POSTGRES_PASSWORD=1234"
      - "POSTGRES_DB=workers_bot_db"