package com.roman.service.stage;

public enum OptionEvent {

    WANT_TO_WATCH_WORKERS,
    WANT_TO_WATCH_ONE_WORKER,
    WANT_TO_CALLING_WORKER,
    WANT_TO_CALLING_WORKER_BY_TIME,

    WANT_TO_OPEN_MEETING_MENU,
    WANT_TO_CREATE_MEETING,
    WANT_TO_ADD_PARTICIPANTS,
    WANT_TO_ADD_TIME,
    WANT_TO_ADD_TITLE,
    WANT_TO_LOOK_MEETING,

    WANT_TO_CHANGE_WORKER_INFORMATION
}
