package com.roman.service.stage;

public enum OptionEvent {

    WANT_TO_WATCH_WORKERS,
    WANT_TO_WATCH_ONE_WORKER,
    WANT_TO_CALLING_WORKER,
    WANT_TO_CALLING_WORKER_BY_TIME,

    WANT_TO_OPEN_MEETING_MENU,
    WANT_TO_CREATE_MEETING,
    WANT_TO_ADD_PARTICIPANTS,
    WANT_TO_ADD_TIME,
    WANT_TO_ADD_TITLE,

    WANT_TO_LOOK_MEETINGS,
    WANT_TO_LOOK_ONE_MEETING_INFO,
    WANT_TO_DELETE_MEETING_INFO,
    WANT_TO_CHANGE_MEETING_INFO,
    WANT_TO_CHANGE_TIME_MEETING,
    WANT_TO_CHANGE_PARTICIPANT_MEETING,
    WANT_TO_ADD_PARTICIPANT_TO_MEETING,
    WANT_TO_REMOVE_PARTICIPANT_FROM_MEETING,

    WANT_TO_CHANGE_WORKER_INFORMATION
}
